### PR TITLE
fix: disabled fullchain textarea editing in SSL details

### LINKED ISSUE #40: bug: SSL certificate fullchain textarea should be editable
### Issue
In SSL Certificate details modal, the full chain textarea is editable.
image

### Expected Behaviour
The textarea should be read-only and have a background of disabled textarea kind o

### PR DESCRIPTION
**Pull request by aybeedee**
Fixes #40 

#### Describe the changes you have made in this PR -

- disabled the fullchain textarea in the SSL certificate details modal

### Screenshots of the changes (If any) -

ssl-texarea-disable

### CODE REVIEW

**Comment by tanmoysrt** [comment]
Hi @aybeedee , just want to know 
do you raise the PR as a part of for hacktoberfest ?
If yes, then I will merge 2 days later

**Review by tanmoysrt — APPROVED** [review]
LGTM :+1:

**Comment by aybeedee** [comment]
> Hi @aybeedee , just want to know do you raise the PR as part of hacktoberfest ? If yes, then I will merge 2 days later

Yes, that would be ideal! Thanks!

**Comment by tanmoysrt** [comment]
Hi @aybeedee
as hacktoberfest started accepting PRs. merging this PR

**Pull request merged**
