### PR TITLE
feat: automatic refresh of the ingress and redirect rules page

### LINKED ISSUE #30: feat: automatic refresh of the `ingress rules` page
### Is your feature request related to a problem? Please describe

Currently, one must manually click the refresh button to refresh the ingress rules page.

### Describe the solution you'd like

1. The page sould be refreshed after a ceratin interval (10 seconds).
2. During refreshing, there should be a spinner in the refresh button.

### Describe alternatives you've considered

_No response_

### Additional context

 
image

### Are you working on this?

No

### LINKED ISSUE #32: feat: automatic refresh of the `redirect rules` page
### Is your feature request related to a problem? Please describe

One must manually click the refresh button to refresh the redirect rules page.

### Describe the solution you'd like

1. The page should be refreshed after a certain interval (10 seconds).
2. During refreshing, there should be a spinner in the refresh button.

### Additional context

 image

### Are you working on this?

No

### PR DESCRIPTION
**Pull request by TMuthu**
Fixes #30 
Fixes #32

#### Describe the changes you have made in this PR -
Added Utility function to refresh data after every 10 seconds and used in ingress rules page.
There are two refresh calls happening after every 10 seconds in redirect rules page, because of multiple re renders. Used this utility function to fix that.

### Screenshots of the changes (If any) -

Note: Please check **Allow edits from maintainers.** before creating the PR.

### CODE REVIEW

**Review by tanmoysrt — APPROVED** [review]
LGTM :rocket:

**Comment by tanmoysrt** [comment]
PR will be merged once Hacktoberfest started!
Meanwhile you can also take a look on other issues related to automatic refresh

**Comment by TMuthu** [comment]
Ok Sure. Assign me the pending issues related to automatic refresh. I will take a look.

**Comment by tanmoysrt** [comment]
> Ok Sure. Assign me the pending issues related to automatic refresh. I will take a look.

Comment down in the issues, so that I can assign you

**Comment by tanmoysrt** [comment]
As hacktoberfest started accepting PRs, merging this PR
image

**Pull request merged**
